[project]
name = "issuepositions"
version = "0.0.1"
dependencies = [
"jupyter",
"ipykernel",
"pandas",
"scikit-learn",
"transformers[torch]",
"datasets",
"pyhere",
"python-dotenv",
"openai",
"pyhere"
]

[project.optional-dependencies]
dev = ["pandas-stubs", "types-PyYAML"]
