name: update quarto render

on:
  push:
    paths:
      - data/intermediate

jobs:
  update_coded_units_csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies using renv
        uses: r-lib/actions/setup-renv@v2

      - name: Render Quarto to update markdown file
        run: |
          src/data-processing/quarto_test/topic_report.qmd --to gfm

      - name: Commit and push changes to .csv file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Quarto update"
          git push
