name: update coded units csv-file

on:
  push
  # test action
  # schedule:
  #   # Runs the workflow every day at 01:00 UTC
  #   - cron: '0 1 * * *'

jobs:
  update_coded_units_csv:
    runs-on: ubuntu-latest

    env:
      - ANNOTINDER_USERNAME: ${{ secrets.ANNOTINDER_USERNAME }}
      - ANNOTINDER_PASSWORD: ${{ secrets.ANNOTINDER_PASSWORD }}
      - CODERS: ${{ secrets.CODERS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies using renv
        uses: r-lib/actions/setup-renv@v2

      - name: Run R script to update csv file
        run: |
          Rscript src/data-processing/irr_report.R

      - name: Commit and push changes to .csv file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/intermediate/coded_units.csv
          git diff --cached --exit-code || git commit -m "[Action update-csv.yml] Updated CSV file"
          git push || echo "No changes to push."
